### ISSUE TITLE
log.Fatal(err) should not be used in a library

### ISSUE THREAD

**Issue by Vovan-VE** [green-api/whatsapp-api-client-golang#12]
The following thing presented in `/pkg/` 18 times. This thing can be in an application and should not be in a library. A library to utilize remote API must not decide how to control the entire application, since it's out of the library scope.

https://github.com/green-api/whatsapp-api-client-golang/blob/8d13379ad93213b063743a2333c61150b27a5865/pkg/api/http.go#L25-L27

Please, replace all of similar app terminations with just `return ..., err`.

**Comment by Amele9** [comment]
@Vovan-VE Thanks for submitting a bug report. The bug has been fixed and the fix is already in the main branch. You can update the library with the command `go get -u github.com/green-api/whatsapp-api-client-golang`.

If you are using a receive-delete mechanism for incoming notifications, I have also added an `ErrorChannel` in the `GreenAPIWebhook` structure so that you can track API errors.

Example:

```go
go func() {
    for {
        select {
        case err := <-GreenAPIWebhook.ErrorChannel:
            fmt.Println(err.Error())
        default:
        <-time.After(time.Second)
        }
    }
}()
```
